version: '3.7'

services:
  web:
    build: ./
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file: .env
    depends_on: 
      - db
      - broker
  worker:
    build: .
    command: celery -A how_distant worker -l INFO --uid=nobody --gid=nogroup
    volumes:
      - .:/app/
    env_file: .env
    depends_on: 
      - db
      - broker
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=distant
      - POSTGRES_PASSWORD=distant
      - POSTGRES_DB=distant
  broker:
    image: redis:alpine
