# Generated by Django 3.0.8 on 2020-09-25 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import surveys.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='survey',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=surveys.models.generate_short_uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(default=surveys.models.generate_short_uuid, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'new'), ('sent', 'sent'), ('error', 'error')], db_index=True, default='new', max_length=10)),
                ('from_phone', models.CharField(default='9293234483', max_length=32)),
                ('to_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('backend_type', models.CharField(choices=[('twilio', 'twilio')], default='twilio', max_length=10)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='surveys.Survey')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
